/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackpackerCard: typeof import('./src/components/BackpackerCard.vue')['default']
    JobList: typeof import('./src/components/JobList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaiwanMap: typeof import('./src/components/TaiwanMap.vue')['default']
  }
}
