/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/applications/[id]': RouteRecordInfo<'/applications/[id]', '/applications/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/backpackers/': RouteRecordInfo<'/backpackers/', '/backpackers', Record<never, never>, Record<never, never>>,
    '/FindHost': RouteRecordInfo<'/FindHost', '/FindHost', Record<never, never>, Record<never, never>>,
    '/host/Job': RouteRecordInfo<'/host/Job', '/host/Job', Record<never, never>, Record<never, never>>,
    '/invitations/[id]': RouteRecordInfo<'/invitations/[id]', '/invitations/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Jobs/[id]': RouteRecordInfo<'/Jobs/[id]', '/Jobs/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/MyResume': RouteRecordInfo<'/MyResume', '/MyResume', Record<never, never>, Record<never, never>>,
    '/Notifications': RouteRecordInfo<'/Notifications', '/Notifications', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/resumes/[id]': RouteRecordInfo<'/resumes/[id]', '/resumes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
